#nullable disable

namespace RemoteDesktop.Host.Forms;

partial class DeviceInventoryDetailsForm
{
    private System.ComponentModel.IContainer components = null;
    private TableLayoutPanel layoutRoot;
    private Panel panelHeader;
    private Button btnRefresh;
    private Button btnExportCsv;
    private Button btnExportExcel;
    private Button btnClose;
    private TableLayoutPanel layoutSummary;
    private Label lblDeviceIdCaption;
    private Label lblDeviceIdValue;
    private Label lblDeviceNameCaption;
    private Label lblDeviceNameValue;
    private Label lblHostNameCaption;
    private Label lblHostNameValue;
    private Label lblAgentVersionCaption;
    private Label lblAgentVersionValue;
    private Label lblResolutionCaption;
    private Label lblResolutionValue;
    private Label lblInventoryCollectedAtCaption;
    private Label lblInventoryCollectedAtValue;
    private Label lblCurrentInventoryTitle;
    private DataGridView gridCurrentInventory;
    private SplitContainer splitMain;
    private Label lblHistoryTitle;
    private DataGridView gridHistory;
    private Label lblSnapshotTitle;
    private DataGridView gridSnapshotDetails;
    private Panel panelStatus;
    private Label lblStatusCaption;
    private Label lblStatusValue;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components is not null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        layoutRoot = new TableLayoutPanel();
        panelHeader = new Panel();
        btnRefresh = new Button();
        btnExportCsv = new Button();
        btnExportExcel = new Button();
        btnClose = new Button();
        layoutSummary = new TableLayoutPanel();
        lblDeviceIdCaption = new Label();
        lblDeviceIdValue = new Label();
        lblDeviceNameCaption = new Label();
        lblDeviceNameValue = new Label();
        lblHostNameCaption = new Label();
        lblHostNameValue = new Label();
        lblAgentVersionCaption = new Label();
        lblAgentVersionValue = new Label();
        lblResolutionCaption = new Label();
        lblResolutionValue = new Label();
        lblInventoryCollectedAtCaption = new Label();
        lblInventoryCollectedAtValue = new Label();
        lblCurrentInventoryTitle = new Label();
        gridCurrentInventory = new DataGridView();
        splitMain = new SplitContainer();
        lblHistoryTitle = new Label();
        gridHistory = new DataGridView();
        lblSnapshotTitle = new Label();
        gridSnapshotDetails = new DataGridView();
        panelStatus = new Panel();
        lblStatusCaption = new Label();
        lblStatusValue = new Label();
        layoutRoot.SuspendLayout();
        panelHeader.SuspendLayout();
        layoutSummary.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)gridCurrentInventory).BeginInit();
        ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
        splitMain.Panel1.SuspendLayout();
        splitMain.Panel2.SuspendLayout();
        splitMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)gridHistory).BeginInit();
        ((System.ComponentModel.ISupportInitialize)gridSnapshotDetails).BeginInit();
        panelStatus.SuspendLayout();
        SuspendLayout();
        layoutRoot.ColumnCount = 1;
        layoutRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        layoutRoot.Controls.Add(panelHeader, 0, 0);
        layoutRoot.Controls.Add(layoutSummary, 0, 1);
        layoutRoot.Controls.Add(lblCurrentInventoryTitle, 0, 2);
        layoutRoot.Controls.Add(gridCurrentInventory, 0, 3);
        layoutRoot.Controls.Add(splitMain, 0, 4);
        layoutRoot.Controls.Add(panelStatus, 0, 5);
        layoutRoot.Dock = DockStyle.Fill;
        layoutRoot.RowCount = 6;
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 68F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 112F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 28F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 150F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        layoutRoot.Size = new Size(1240, 860);
        panelHeader.Controls.Add(btnRefresh);
        panelHeader.Controls.Add(btnExportCsv);
        panelHeader.Controls.Add(btnExportExcel);
        panelHeader.Controls.Add(btnClose);
        panelHeader.Dock = DockStyle.Fill;
        panelHeader.Location = new Point(3, 3);
        panelHeader.Size = new Size(1234, 62);
        btnRefresh.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnRefresh.Location = new Point(786, 10);
        btnRefresh.Size = new Size(108, 42);
        btnRefresh.Click += btnRefresh_Click;
        btnExportCsv.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnExportCsv.Location = new Point(900, 10);
        btnExportCsv.Size = new Size(108, 42);
        btnExportCsv.Click += btnExportCsv_Click;
        btnExportExcel.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnExportExcel.Location = new Point(1014, 10);
        btnExportExcel.Size = new Size(108, 42);
        btnExportExcel.Click += btnExportExcel_Click;
        btnClose.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnClose.DialogResult = DialogResult.OK;
        btnClose.Location = new Point(1128, 10);
        btnClose.Size = new Size(96, 42);
        layoutSummary.ColumnCount = 4;
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 17F));
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 17F));
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33F));
        layoutSummary.Controls.Add(lblDeviceIdCaption, 0, 0);
        layoutSummary.Controls.Add(lblDeviceIdValue, 1, 0);
        layoutSummary.Controls.Add(lblDeviceNameCaption, 2, 0);
        layoutSummary.Controls.Add(lblDeviceNameValue, 3, 0);
        layoutSummary.Controls.Add(lblHostNameCaption, 0, 1);
        layoutSummary.Controls.Add(lblHostNameValue, 1, 1);
        layoutSummary.Controls.Add(lblAgentVersionCaption, 2, 1);
        layoutSummary.Controls.Add(lblAgentVersionValue, 3, 1);
        layoutSummary.Controls.Add(lblResolutionCaption, 0, 2);
        layoutSummary.Controls.Add(lblResolutionValue, 1, 2);
        layoutSummary.Controls.Add(lblInventoryCollectedAtCaption, 2, 2);
        layoutSummary.Controls.Add(lblInventoryCollectedAtValue, 3, 2);
        layoutSummary.Dock = DockStyle.Fill;
        layoutSummary.Location = new Point(3, 71);
        layoutSummary.Size = new Size(1234, 106);
        layoutSummary.RowCount = 3;
        for (var index = 0; index < 3; index++)
        {
            layoutSummary.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
        }
        lblCurrentInventoryTitle.AutoSize = true;
        lblCurrentInventoryTitle.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold, GraphicsUnit.Point);
        lblCurrentInventoryTitle.Location = new Point(3, 180);
        gridCurrentInventory.AutoGenerateColumns = false;
        gridCurrentInventory.AllowUserToAddRows = false;
        gridCurrentInventory.AllowUserToDeleteRows = false;
        gridCurrentInventory.ReadOnly = true;
        gridCurrentInventory.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridCurrentInventory.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridCurrentInventory.Dock = DockStyle.Fill;
        gridCurrentInventory.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Field", FillWeight = 28F });
        gridCurrentInventory.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Value", FillWeight = 72F });
        splitMain.Dock = DockStyle.Fill;
        splitMain.Location = new Point(3, 361);
        splitMain.Size = new Size(1234, 452);
        splitMain.SplitterDistance = 640;
        splitMain.Panel1.Controls.Add(gridHistory);
        splitMain.Panel1.Controls.Add(lblHistoryTitle);
        splitMain.Panel2.Controls.Add(gridSnapshotDetails);
        splitMain.Panel2.Controls.Add(lblSnapshotTitle);
        lblHistoryTitle.AutoSize = true;
        lblHistoryTitle.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold, GraphicsUnit.Point);
        lblHistoryTitle.Location = new Point(8, 8);
        gridHistory.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        gridHistory.AutoGenerateColumns = false;
        gridHistory.AllowUserToAddRows = false;
        gridHistory.AllowUserToDeleteRows = false;
        gridHistory.ReadOnly = true;
        gridHistory.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridHistory.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridHistory.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "CollectedAt", FillWeight = 18F });
        gridHistory.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "RecordedAt", FillWeight = 18F });
        gridHistory.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Summary", FillWeight = 52F });
        gridHistory.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Fingerprint", FillWeight = 12F });
        gridHistory.Location = new Point(8, 36);
        gridHistory.Size = new Size(622, 406);
        gridHistory.SelectionChanged += gridHistory_SelectionChanged;
        lblSnapshotTitle.AutoSize = true;
        lblSnapshotTitle.Font = new Font("Microsoft JhengHei UI", 10F, FontStyle.Bold, GraphicsUnit.Point);
        lblSnapshotTitle.Location = new Point(8, 8);
        gridSnapshotDetails.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        gridSnapshotDetails.AutoGenerateColumns = false;
        gridSnapshotDetails.AllowUserToAddRows = false;
        gridSnapshotDetails.AllowUserToDeleteRows = false;
        gridSnapshotDetails.ReadOnly = true;
        gridSnapshotDetails.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridSnapshotDetails.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridSnapshotDetails.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Field", FillWeight = 30F });
        gridSnapshotDetails.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Value", FillWeight = 70F });
        gridSnapshotDetails.Location = new Point(8, 36);
        gridSnapshotDetails.Size = new Size(570, 406);
        panelStatus.Controls.Add(lblStatusCaption);
        panelStatus.Controls.Add(lblStatusValue);
        panelStatus.Dock = DockStyle.Fill;
        panelStatus.Location = new Point(3, 819);
        panelStatus.Size = new Size(1234, 38);
        lblStatusCaption.AutoSize = true;
        lblStatusCaption.Location = new Point(10, 11);
        lblStatusValue.AutoSize = true;
        lblStatusValue.Location = new Point(80, 11);
        Text = "裝置詳細資訊 / Device details";
        ClientSize = new Size(1240, 860);
        Controls.Add(layoutRoot);
        MinimumSize = new Size(1180, 780);
        StartPosition = FormStartPosition.CenterParent;
        layoutRoot.ResumeLayout(false);
        layoutRoot.PerformLayout();
        panelHeader.ResumeLayout(false);
        layoutSummary.ResumeLayout(false);
        layoutSummary.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)gridCurrentInventory).EndInit();
        splitMain.Panel1.ResumeLayout(false);
        splitMain.Panel1.PerformLayout();
        splitMain.Panel2.ResumeLayout(false);
        splitMain.Panel2.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
        splitMain.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)gridHistory).EndInit();
        ((System.ComponentModel.ISupportInitialize)gridSnapshotDetails).EndInit();
        panelStatus.ResumeLayout(false);
        panelStatus.PerformLayout();
        ResumeLayout(false);
    }
}
