#nullable disable
namespace RemoteDesktop.Host.Forms;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null;
    private TableLayoutPanel layoutRoot;
    private Panel panelHeader;
    private Label lblTitle;
    private Button btnRefresh;
    private Button btnOpenViewer;
    private TableLayoutPanel layoutSummary;
    private Label lblConsoleNameCaption;
    private Label lblConsoleNameValue;
    private Label lblServerUrlCaption;
    private Label lblServerUrlValue;
    private Label lblHealthUrlCaption;
    private Label lblHealthUrlValue;
    private Label lblSignedInUserCaption;
    private Label lblSignedInUserValue;
    private Label lblOnlineCountCaption;
    private Label lblOnlineCountValue;
    private Label lblTotalCountCaption;
    private Label lblTotalCountValue;
    private Label lblLastRefreshCaption;
    private Label lblLastRefreshValue;
    private SplitContainer splitMain;
    private DataGridView gridDevices;
    private DataGridView gridLogs;
    private Label lblDevicesTitle;
    private Label lblLogsTitle;
    private Panel panelStatus;
    private Label lblStatusCaption;
    private Label lblStatusValue;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components is not null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        layoutRoot = new TableLayoutPanel();
        panelHeader = new Panel();
        btnOpenViewer = new Button();
        btnRefresh = new Button();
        lblTitle = new Label();
        layoutSummary = new TableLayoutPanel();
        lblConsoleNameCaption = new Label();
        lblConsoleNameValue = new Label();
        lblServerUrlCaption = new Label();
        lblServerUrlValue = new Label();
        lblHealthUrlCaption = new Label();
        lblHealthUrlValue = new Label();
        lblSignedInUserCaption = new Label();
        lblSignedInUserValue = new Label();
        lblOnlineCountCaption = new Label();
        lblOnlineCountValue = new Label();
        lblTotalCountCaption = new Label();
        lblTotalCountValue = new Label();
        lblLastRefreshCaption = new Label();
        lblLastRefreshValue = new Label();
        splitMain = new SplitContainer();
        gridDevices = new DataGridView();
        gridLogs = new DataGridView();
        lblDevicesTitle = new Label();
        lblLogsTitle = new Label();
        panelStatus = new Panel();
        lblStatusCaption = new Label();
        lblStatusValue = new Label();
        layoutRoot.SuspendLayout();
        panelHeader.SuspendLayout();
        layoutSummary.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)splitMain).BeginInit();
        splitMain.Panel1.SuspendLayout();
        splitMain.Panel2.SuspendLayout();
        splitMain.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)gridDevices).BeginInit();
        ((System.ComponentModel.ISupportInitialize)gridLogs).BeginInit();
        panelStatus.SuspendLayout();
        SuspendLayout();
        layoutRoot.ColumnCount = 1;
        layoutRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        layoutRoot.Controls.Add(panelHeader, 0, 0);
        layoutRoot.Controls.Add(layoutSummary, 0, 1);
        layoutRoot.Controls.Add(splitMain, 0, 2);
        layoutRoot.Controls.Add(panelStatus, 0, 3);
        layoutRoot.Dock = DockStyle.Fill;
        layoutRoot.Location = new Point(0, 0);
        layoutRoot.Name = "layoutRoot";
        layoutRoot.RowCount = 4;
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 72F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 110F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        layoutRoot.Size = new Size(1384, 861);
        panelHeader.Controls.Add(btnOpenViewer);
        panelHeader.Controls.Add(btnRefresh);
        panelHeader.Controls.Add(lblTitle);
        panelHeader.Dock = DockStyle.Fill;
        panelHeader.Location = new Point(3, 3);
        panelHeader.Name = "panelHeader";
        panelHeader.Size = new Size(1378, 66);
        btnOpenViewer.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnOpenViewer.Enabled = false;
        btnOpenViewer.Location = new Point(1151, 18);
        btnOpenViewer.Name = "btnOpenViewer";
        btnOpenViewer.Size = new Size(108, 34);
        btnOpenViewer.TabIndex = 1;
        btnOpenViewer.Text = "開啟遠端畫面";
        btnOpenViewer.UseVisualStyleBackColor = true;
        btnOpenViewer.Click += btnOpenViewer_Click;
        btnRefresh.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnRefresh.Location = new Point(1265, 18);
        btnRefresh.Name = "btnRefresh";
        btnRefresh.Size = new Size(98, 34);
        btnRefresh.TabIndex = 2;
        btnRefresh.Text = "重新整理";
        btnRefresh.UseVisualStyleBackColor = true;
        btnRefresh.Click += btnRefresh_Click;
        lblTitle.AutoSize = true;
        lblTitle.Font = new Font("Microsoft JhengHei UI", 18F, FontStyle.Bold, GraphicsUnit.Point);
        lblTitle.Location = new Point(16, 18);
        lblTitle.Name = "lblTitle";
        lblTitle.Size = new Size(326, 30);
        lblTitle.Text = "RemoteDesktop Windows 主控台";
        layoutSummary.ColumnCount = 4;
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 34F));
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 16F));
        layoutSummary.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 34F));
        layoutSummary.Controls.Add(lblConsoleNameCaption, 0, 0);
        layoutSummary.Controls.Add(lblConsoleNameValue, 1, 0);
        layoutSummary.Controls.Add(lblServerUrlCaption, 2, 0);
        layoutSummary.Controls.Add(lblServerUrlValue, 3, 0);
        layoutSummary.Controls.Add(lblHealthUrlCaption, 0, 1);
        layoutSummary.Controls.Add(lblHealthUrlValue, 1, 1);
        layoutSummary.Controls.Add(lblSignedInUserCaption, 2, 1);
        layoutSummary.Controls.Add(lblSignedInUserValue, 3, 1);
        layoutSummary.Controls.Add(lblOnlineCountCaption, 0, 2);
        layoutSummary.Controls.Add(lblOnlineCountValue, 1, 2);
        layoutSummary.Controls.Add(lblTotalCountCaption, 2, 2);
        layoutSummary.Controls.Add(lblTotalCountValue, 3, 2);
        layoutSummary.Controls.Add(lblLastRefreshCaption, 0, 3);
        layoutSummary.Controls.Add(lblLastRefreshValue, 1, 3);
        layoutSummary.Dock = DockStyle.Fill;
        layoutSummary.Location = new Point(3, 75);
        layoutSummary.Name = "layoutSummary";
        layoutSummary.RowCount = 4;
        layoutSummary.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        layoutSummary.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        layoutSummary.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        layoutSummary.RowStyles.Add(new RowStyle(SizeType.Percent, 25F));
        layoutSummary.Size = new Size(1378, 104);
        lblConsoleNameCaption.AutoSize = true;
        lblConsoleNameCaption.Text = "主控台名稱";
        lblConsoleNameValue.AutoSize = true;
        lblConsoleNameValue.Text = "-";
        lblServerUrlCaption.AutoSize = true;
        lblServerUrlCaption.Text = "Agent 端點";
        lblServerUrlValue.AutoSize = true;
        lblServerUrlValue.Text = "-";
        lblHealthUrlCaption.AutoSize = true;
        lblHealthUrlCaption.Text = "健康檢查位";
        lblHealthUrlValue.AutoSize = true;
        lblHealthUrlValue.Text = "-";
        lblSignedInUserCaption.AutoSize = true;
        lblSignedInUserCaption.Text = "目前登入者";
        lblSignedInUserValue.AutoSize = true;
        lblSignedInUserValue.Text = "-";
        lblOnlineCountCaption.AutoSize = true;
        lblOnlineCountCaption.Text = "在線裝置";
        lblOnlineCountValue.AutoSize = true;
        lblOnlineCountValue.Text = "0";
        lblTotalCountCaption.AutoSize = true;
        lblTotalCountCaption.Text = "裝置總數";
        lblTotalCountValue.AutoSize = true;
        lblTotalCountValue.Text = "0";
        lblLastRefreshCaption.AutoSize = true;
        lblLastRefreshCaption.Text = "最後更新";
        lblLastRefreshValue.AutoSize = true;
        lblLastRefreshValue.Text = "-";
        splitMain.Dock = DockStyle.Fill;
        splitMain.Location = new Point(3, 185);
        splitMain.Name = "splitMain";
        splitMain.Orientation = Orientation.Horizontal;
        splitMain.Panel1.Controls.Add(gridDevices);
        splitMain.Panel1.Controls.Add(lblDevicesTitle);
        splitMain.Panel2.Controls.Add(gridLogs);
        splitMain.Panel2.Controls.Add(lblLogsTitle);
        splitMain.Size = new Size(1378, 633);
        splitMain.SplitterDistance = 315;
        lblDevicesTitle.AutoSize = true;
        lblDevicesTitle.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        lblDevicesTitle.Location = new Point(10, 9);
        lblDevicesTitle.Text = "設備與在線狀態";
        gridDevices.AllowUserToAddRows = false;
        gridDevices.AllowUserToDeleteRows = false;
        gridDevices.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        gridDevices.AutoGenerateColumns = false;
        gridDevices.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridDevices.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        gridDevices.Location = new Point(10, 37);
        gridDevices.MultiSelect = false;
        gridDevices.ReadOnly = true;
        gridDevices.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridDevices.Size = new Size(1359, 266);
        gridDevices.CellDoubleClick += gridDevices_CellDoubleClick;
        gridDevices.SelectionChanged += gridDevices_SelectionChanged;
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "StatusText", HeaderText = "狀態", FillWeight = 70F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "DeviceId", HeaderText = "DeviceId", FillWeight = 110F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "DeviceName", HeaderText = "裝置名稱", FillWeight = 120F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "HostName", HeaderText = "主機名稱", FillWeight = 110F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Resolution", HeaderText = "解析度", FillWeight = 90F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "AgentVersion", HeaderText = "版本", FillWeight = 80F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "LastSeenAt", HeaderText = "最後心跳", FillWeight = 110F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "LastConnectedAt", HeaderText = "最近連線", FillWeight = 110F });
        gridDevices.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "LastDisconnectedAt", HeaderText = "最近離線", FillWeight = 110F });
        lblLogsTitle.AutoSize = true;
        lblLogsTitle.Font = new Font("Microsoft JhengHei UI", 11F, FontStyle.Bold, GraphicsUnit.Point);
        lblLogsTitle.Location = new Point(10, 9);
        lblLogsTitle.Text = "連線歷程與紀錄";
        gridLogs.AllowUserToAddRows = false;
        gridLogs.AllowUserToDeleteRows = false;
        gridLogs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
        gridLogs.AutoGenerateColumns = false;
        gridLogs.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        gridLogs.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        gridLogs.Location = new Point(10, 37);
        gridLogs.MultiSelect = false;
        gridLogs.ReadOnly = true;
        gridLogs.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        gridLogs.Size = new Size(1359, 263);
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "DeviceId", HeaderText = "DeviceId", FillWeight = 95F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "DeviceName", HeaderText = "裝置名稱", FillWeight = 110F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "HostName", HeaderText = "主機名稱", FillWeight = 110F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "ConnectedAt", HeaderText = "連線時間", FillWeight = 115F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "LastSeenAt", HeaderText = "最後心跳", FillWeight = 115F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "DisconnectedAt", HeaderText = "離線時間", FillWeight = 115F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "DisconnectReason", HeaderText = "離線原因", FillWeight = 120F });
        gridLogs.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "OnlineSeconds", HeaderText = "在線秒數", FillWeight = 80F });
        panelStatus.Controls.Add(lblStatusValue);
        panelStatus.Controls.Add(lblStatusCaption);
        panelStatus.Dock = DockStyle.Fill;
        panelStatus.Location = new Point(3, 824);
        panelStatus.Name = "panelStatus";
        panelStatus.Size = new Size(1378, 34);
        lblStatusCaption.AutoSize = true;
        lblStatusCaption.Location = new Point(16, 9);
        lblStatusCaption.Text = "狀態";
        lblStatusValue.AutoSize = true;
        lblStatusValue.Location = new Point(59, 9);
        lblStatusValue.Text = "就緒";
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1384, 861);
        Controls.Add(layoutRoot);
        MinimumSize = new Size(1180, 760);
        Name = "MainForm";
        StartPosition = FormStartPosition.CenterScreen;
        Text = "RemoteDesktop Windows 主控台";
        layoutRoot.ResumeLayout(false);
        panelHeader.ResumeLayout(false);
        panelHeader.PerformLayout();
        layoutSummary.ResumeLayout(false);
        layoutSummary.PerformLayout();
        splitMain.Panel1.ResumeLayout(false);
        splitMain.Panel1.PerformLayout();
        splitMain.Panel2.ResumeLayout(false);
        splitMain.Panel2.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)splitMain).EndInit();
        splitMain.ResumeLayout(false);
        ((System.ComponentModel.ISupportInitialize)gridDevices).EndInit();
        ((System.ComponentModel.ISupportInitialize)gridLogs).EndInit();
        panelStatus.ResumeLayout(false);
        panelStatus.PerformLayout();
        ResumeLayout(false);
    }
}
#nullable restore
