#nullable disable
namespace RemoteDesktop.Host.Forms;

partial class RemoteViewerForm
{
    private System.ComponentModel.IContainer components = null;
    private TableLayoutPanel layoutRoot;
    private Panel panelTop;
    private Label lblDeviceCaption;
    private Label lblDeviceValue;
    private Label lblHostCaption;
    private Label lblHostValue;
    private Label lblResolutionCaption;
    private Label lblResolutionValue;
    private Label lblStatusCaption;
    private Label lblStatusValue;
    private Label lblClipboardCaption;
    private Label lblClipboardValue;
    private Label lblTransferCaption;
    private Label lblTransferValue;
    private ProgressBar progressFileTransfer;
    private Button btnGetClipboard;
    private Button btnSendClipboard;
    private Button btnUploadFile;
    private Button btnFocusRemote;
    private Button btnDisconnect;
    private PictureBox pictureStream;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components is not null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        layoutRoot = new TableLayoutPanel();
        panelTop = new Panel();
        btnDisconnect = new Button();
        btnFocusRemote = new Button();
        btnUploadFile = new Button();
        btnGetClipboard = new Button();
        btnSendClipboard = new Button();
        progressFileTransfer = new ProgressBar();
        lblTransferValue = new Label();
        lblTransferCaption = new Label();
        lblClipboardValue = new Label();
        lblClipboardCaption = new Label();
        lblStatusValue = new Label();
        lblStatusCaption = new Label();
        lblResolutionValue = new Label();
        lblResolutionCaption = new Label();
        lblHostValue = new Label();
        lblHostCaption = new Label();
        lblDeviceValue = new Label();
        lblDeviceCaption = new Label();
        pictureStream = new PictureBox();
        layoutRoot.SuspendLayout();
        panelTop.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)pictureStream).BeginInit();
        SuspendLayout();
        layoutRoot.ColumnCount = 1;
        layoutRoot.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        layoutRoot.Controls.Add(panelTop, 0, 0);
        layoutRoot.Controls.Add(pictureStream, 0, 1);
        layoutRoot.Dock = DockStyle.Fill;
        layoutRoot.Location = new Point(0, 0);
        layoutRoot.Name = "layoutRoot";
        layoutRoot.RowCount = 2;
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Absolute, 188F));
        layoutRoot.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        layoutRoot.Size = new Size(1420, 860);
        panelTop.Controls.Add(btnDisconnect);
        panelTop.Controls.Add(btnFocusRemote);
        panelTop.Controls.Add(btnUploadFile);
        panelTop.Controls.Add(btnGetClipboard);
        panelTop.Controls.Add(btnSendClipboard);
        panelTop.Controls.Add(progressFileTransfer);
        panelTop.Controls.Add(lblTransferValue);
        panelTop.Controls.Add(lblTransferCaption);
        panelTop.Controls.Add(lblClipboardValue);
        panelTop.Controls.Add(lblClipboardCaption);
        panelTop.Controls.Add(lblStatusValue);
        panelTop.Controls.Add(lblStatusCaption);
        panelTop.Controls.Add(lblResolutionValue);
        panelTop.Controls.Add(lblResolutionCaption);
        panelTop.Controls.Add(lblHostValue);
        panelTop.Controls.Add(lblHostCaption);
        panelTop.Controls.Add(lblDeviceValue);
        panelTop.Controls.Add(lblDeviceCaption);
        panelTop.Dock = DockStyle.Fill;
        panelTop.Location = new Point(3, 3);
        panelTop.Name = "panelTop";
        panelTop.Size = new Size(1414, 182);
        btnDisconnect.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnDisconnect.Location = new Point(1294, 18);
        btnDisconnect.Name = "btnDisconnect";
        btnDisconnect.Size = new Size(105, 46);
        btnDisconnect.Text = "Disconnect";
        btnDisconnect.UseVisualStyleBackColor = true;
        btnDisconnect.Click += btnDisconnect_Click;
        btnFocusRemote.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnFocusRemote.Location = new Point(1178, 18);
        btnFocusRemote.Name = "btnFocusRemote";
        btnFocusRemote.Size = new Size(110, 46);
        btnFocusRemote.Text = "Focus Viewer";
        btnFocusRemote.UseVisualStyleBackColor = true;
        btnFocusRemote.Click += btnFocusRemote_Click;
        btnUploadFile.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnUploadFile.Location = new Point(1062, 18);
        btnUploadFile.Name = "btnUploadFile";
        btnUploadFile.Size = new Size(110, 46);
        btnUploadFile.Text = "Upload File";
        btnUploadFile.UseVisualStyleBackColor = true;
        btnUploadFile.Click += btnUploadFile_Click;
        btnGetClipboard.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnGetClipboard.Location = new Point(946, 18);
        btnGetClipboard.Name = "btnGetClipboard";
        btnGetClipboard.Size = new Size(110, 46);
        btnGetClipboard.Text = "Get Clipboard";
        btnGetClipboard.UseVisualStyleBackColor = true;
        btnGetClipboard.Click += btnGetClipboard_Click;
        btnSendClipboard.Anchor = AnchorStyles.Top | AnchorStyles.Right;
        btnSendClipboard.Location = new Point(800, 18);
        btnSendClipboard.Name = "btnSendClipboard";
        btnSendClipboard.Size = new Size(136, 46);
        btnSendClipboard.Text = "Send Clipboard";
        btnSendClipboard.UseVisualStyleBackColor = true;
        btnSendClipboard.Click += btnSendClipboard_Click;
        lblDeviceCaption.AutoSize = false;
        lblDeviceCaption.Location = new Point(18, 16);
        lblDeviceCaption.Size = new Size(108, 32);
        lblDeviceCaption.Text = "Device";
        lblDeviceValue.AutoSize = true;
        lblDeviceValue.Location = new Point(140, 16);
        lblDeviceValue.Text = "-";
        lblHostCaption.AutoSize = false;
        lblHostCaption.Location = new Point(18, 52);
        lblHostCaption.Size = new Size(108, 32);
        lblHostCaption.Text = "Host";
        lblHostValue.AutoSize = true;
        lblHostValue.Location = new Point(140, 52);
        lblHostValue.Text = "-";
        lblResolutionCaption.AutoSize = false;
        lblResolutionCaption.Location = new Point(360, 16);
        lblResolutionCaption.Size = new Size(108, 32);
        lblResolutionCaption.Text = "Resolution";
        lblResolutionValue.AutoSize = true;
        lblResolutionValue.Location = new Point(482, 16);
        lblResolutionValue.Text = "-";
        lblStatusCaption.AutoSize = false;
        lblStatusCaption.Location = new Point(360, 52);
        lblStatusCaption.Size = new Size(108, 32);
        lblStatusCaption.Text = "Status";
        lblStatusValue.AutoSize = true;
        lblStatusValue.Location = new Point(482, 52);
        lblStatusValue.Text = "-";
        lblClipboardCaption.AutoSize = false;
        lblClipboardCaption.Location = new Point(18, 98);
        lblClipboardCaption.Size = new Size(108, 32);
        lblClipboardCaption.Text = "Clipboard";
        lblClipboardValue.AutoSize = true;
        lblClipboardValue.Location = new Point(140, 98);
        lblClipboardValue.Text = "-";
        lblTransferCaption.AutoSize = false;
        lblTransferCaption.Location = new Point(18, 138);
        lblTransferCaption.Size = new Size(108, 32);
        lblTransferCaption.Text = "Transfer";
        lblTransferValue.AutoSize = true;
        lblTransferValue.Location = new Point(140, 138);
        lblTransferValue.Text = "-";
        progressFileTransfer.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        progressFileTransfer.Location = new Point(140, 161);
        progressFileTransfer.Maximum = 100;
        progressFileTransfer.Name = "progressFileTransfer";
        progressFileTransfer.Size = new Size(1259, 16);
        progressFileTransfer.Style = ProgressBarStyle.Continuous;
        pictureStream.BackColor = Color.Black;
        pictureStream.Dock = DockStyle.Fill;
        pictureStream.Location = new Point(3, 191);
        pictureStream.Name = "pictureStream";
        pictureStream.Size = new Size(1414, 666);
        pictureStream.SizeMode = PictureBoxSizeMode.Zoom;
        pictureStream.TabStop = true;
        pictureStream.MouseDown += pictureStream_MouseDown;
        pictureStream.MouseMove += pictureStream_MouseMove;
        pictureStream.MouseUp += pictureStream_MouseUp;
        pictureStream.MouseWheel += pictureStream_MouseWheel;
        AutoScaleDimensions = new SizeF(7F, 15F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1420, 860);
        Controls.Add(layoutRoot);
        MinimumSize = new Size(1040, 720);
        Name = "RemoteViewerForm";
        StartPosition = FormStartPosition.CenterParent;
        Text = "Remote Viewer";
        KeyDown += RemoteViewerForm_KeyDown;
        KeyPress += RemoteViewerForm_KeyPress;
        KeyUp += RemoteViewerForm_KeyUp;
        layoutRoot.ResumeLayout(false);
        panelTop.ResumeLayout(false);
        panelTop.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)pictureStream).EndInit();
        ResumeLayout(false);
    }
}
#nullable restore
